name: esw_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  intl: ^0.19.0
  fl_chart: ^0.66.2
  fluttertoast: ^8.2.4
  device_info_plus: ^9.1.2
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
