name: esw_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  intl: ^0.19.0
  path_provider: ^2.1.3
  csv: ^6.0.0
  file_picker: ^8.0.3
  fluttertoast: ^8.2.4
  device_info_plus: ^10.1.0
  network_info_plus: ^5.0.3
  http: ^1.2.1
  html_unescape: ^2.0.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
